FROM registry.suse.com/bci/golang:1.22

ARG DAPPER_HOST_ARCH
ENV HOST_ARCH=${DAPPER_HOST_ARCH} ARCH=${DAPPER_HOST_ARCH}

RUN zypper refresh
RUN go install golang.org/x/lint/golint@latest

ENV DAPPER_ENV REPO TAG
ENV DAPPER_SOURCE /go/src/github.com/rancher/loglevel
ENV DAPPER_OUTPUT ./bin ./dist
ENV DAPPER_DOCKER_SOCKET true
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
