#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../bin

mkdir -p ../dist/artifacts
tar cvzf ../dist/artifacts/loglevel-${ARCH}-${VERSION}.tar.gz .

echo "Built loglevel-${ARCH}-${VERSION}.tar.gz"

