#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

PACKAGES="$(go list ./...)"

echo Running: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"

if ! command -v golangci-lint; then
    echo "Skipping validation on ARCH's other than linux amd64"
    exit
fi

echo Running: golangci-lint
golangci-lint run


